---
# handlers file for redash
- name: restart redash
  service: name=redash state=restarted

- name: rebuild redash
  command: /usr/bin/docker-compose build chdir={{ redash_home }}
  notify: initialise redash

- name: initialise redash
  command: /usr/bin/docker-compose run --rm server create_db chdir={{ redash_home }}
  ignore_errors: yes
  notify:
    - restart redash

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  notify: restart redash